name: cenv
channels:
  - conda-forge
  - defaults
  - pytorch
  - bioconda
dependencies:
  - python=3.7.3
  - conda-build=3.18.9
  - pip=19.1.1
  - mypy=0.720
  - pylint=2.4.4
  - ipython=7.10.1
  - matplotlib=3.1.0
  - pytest=4.6.3
  - pytorch=1.4.0
  - torchvision=0.3.0
  - pandas=0.25.1
  - scikit-learn=0.21.2
  - nltk=3.4.5
  - osqp=0.6.1
  - pip:
    - snakemake==5.10.0
    - click==7.0
    - wandb==0.8.28
    - isort==4.3.21
    - pyflakes==2.1.1
    - OpenNMT-py==1.0.1
    - fairseq==0.9.0
    - spacy==2.2.1
    # uncomment for spacy models
    #- https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.2.0/en_core_web_md-2.2.0.tar.gz
    - black==19.10b0
    - pytest-xdist==1.31.0


